


#sensor yr:
- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - pressure
    - humidity

#sensor wunderground:
- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - alerts
    - pressure_mb
    - pressure_trend
    - relative_humidity
    - observation_time
    - temp_c
    - weather


#sensor random:
- platform: random
  name: random
  minimum: 0
  maximum: 200


#sensor efergy:
- platform: efergy
  name: efergy
  app_token: !secret efergy_app_token
  utc_offset: -300
  monitored_variables:
    - type: amount
      period: day
    - type: current_values 

# raspberry pi system monitor
- platform: command_line
  name: CPU Temp
  command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "ºC"
  value_template: '{{ value | multiply(0.001) }}'

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: memory_use_percent
  - type: processor_use
  - type: since_last_boot
  #- type: network_in
  #  arg: eth0
  #- type: network_out
  #  arg: eth0


